steps:
# 1. Compilar el proyecto
  - name: 'maven:3.9.6-eclipse-temurin-21'
    entrypoint: mvn
    args: ['clean', 'package', '-DskipTests']
    dir: 'backend'

# 2. Construir la imagen Docker (Ajustado para entrar a la carpeta backend)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'us-central1-docker.pkg.dev/api-de-skincare/cloud-run-source-deploy/skincare-api:$COMMIT_SHA',
        '-t', 'us-central1-docker.pkg.dev/api-de-skincare/cloud-run-source-deploy/skincare-api:latest',
        'backend' 
      ]

# 3. Push de la imagen
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        '--all-tags',
        'us-central1-docker.pkg.dev/api-de-skincare/cloud-run-source-deploy/skincare-api'
      ]

# 4. Deploy a Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'services',
        'update',
        'skincare-api',
        '--image=us-central1-docker.pkg.dev/api-de-skincare/cloud-run-source-deploy/skincare-api:$COMMIT_SHA',
        '--region=us-central1',
        '--quiet'
      ]

options:
  logging: CLOUD_LOGGING_ONLY