spring.application.name=skincare-api
server.port=${PORT:8080}

# URL para Cloud SQL (Asegúrate de que no haya espacios al final)
spring.datasource.url=jdbc:postgresql:///${DB_NAME}?cloudSqlInstance=${INSTANCE_CONNECTION_NAME}&socketFactory=com.google.cloud.sql.postgres.SocketFactory
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Forzar el driver correcto
spring.datasource.driver-class-name=org.postgresql.Driver

# IMPORTANTE: Desactiva la validación de DDL al inicio para evitar que el contenedor tarde mucho y falle el timeout
spring.jpa.hibernate.ddl-auto=none 
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect