spring.application.name=estudiantes-api
spring.web.resources.static-locations=classpath:/static/
server.port=9090
 
spring.jpa.database=POSTGRESQL
spring.sql.init.platform=postgres
    spring.datasource.url=jdbc:postgresql://localhost:5432/skincare_db
    spring.datasource.username=postgres
spring.datasource.password=Aa1002416662
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update