spring.application.name=skincare-api

# 🔥 Puerto dinámico (Cloud Run)
server.port=${PORT:8080}

# 🔥 Perfil por defecto (LOCAL)
spring.profiles.active=dev

# 🔥 JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# (Opcional)
spring.web.resources.static-locations=classpath:/static/

# 🔥 Base de datos LOCAL
spring.datasource.url=jdbc:postgresql://localhost:5432/skincare_db


spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=5

# 🔥 Base de datos CLOUD SQL
spring.datasource.url=jdbc:postgresql:///skincare?cloudSqlInstance=${INSTANCE_CONNECTION_NAME}&socketFactory=com.google.cloud.sql.postgres.SocketFactory
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=2