server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://34.59.253.155:5432/skincare_db
spring.datasource.username=postgres
spring.datasource.password=Aa1002416662

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=2